import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/organisms/Header/Header";
import SectionTitle from "../components/atomic/SectionTitle/SectionTitle";
import styles from "../styles/layout.module.scss";
import Hero from "../components/molecules/Hero/Hero";

const Project: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SectionTitle>Home</SectionTitle>
    </div>
  );
};

export default Project;
